# -*- coding: utf-8 -*-
"""Saude/bem estar  - Recomendação de viagem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4PUNq2G6Vg8YLoVsTjVL1bC6J1dDLVI
"""

import pandas as pd
from io import StringIO
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Dados baseados na imagem
dados_viagens_str = """
Destino,Tipo_Viagem,Duracao,Interesse,Estacao
Paris,Cultural,Curta,Arte,Primavera
Cancun,Praia,Curta,Relaxamento,Verao
NovaYork,Urbana,Curta,Compras,Outono
Alpes,Natureza,Longa,Aventura,Inverno
Kyoto,Cultural,Longa,Historia,Outono
RioDeJaneiro,Praia,Curta,Festa,Verao
Amazonas,Natureza,Longa,Ecoturismo,Verao
Londres,Urbana,Curta,Arte,Outono
Buzios,Praia,Curta,Relaxamento,Verao
MachuPicchu,Cultural,Longa,Historia,Primavera
"""

df_viagens = pd.read_csv(StringIO(dados_viagens_str))

# --- Vetorização (One-Hot Encoding) ---
# Converte todas as colunas categóricas em representação binária (0 ou 1)
df_features = pd.get_dummies(df_viagens.drop('Destino', axis=1))

# Armazena a matriz de features e os nomes dos destinos separadamente
matriz_features = df_features.values
destinos = df_viagens['Destino'].tolist()

print("--- Matriz de Features Vetorizadas Pronta ---")
print(f"Dimensões da Matriz: {matriz_features.shape}")
print(f"Features: {df_features.columns.tolist()}")

def recomendar_destino(preferencias_usuario, df_features, destinos, matriz_features, k=3):

    # 1. Converte as preferências do usuário para o vetor de features
    # Criamos um DataFrame temporário com a entrada do usuário para aplicar o One-Hot Encoding
    df_usuario = pd.DataFrame([preferencias_usuario])

    # Aplicamos o One-Hot Encoding e re-alinhamos as colunas
    # Isso é CRUCIAL: garante que o vetor do usuário tenha exatamente as mesmas colunas (e na mesma ordem)
    # que a matriz de features do dataset.
    df_usuario_encoded = pd.get_dummies(df_usuario).reindex(columns=df_features.columns, fill_value=0)

    # Se todas as features forem zero (o que não deve ocorrer se houver correspondência), retornamos o erro
    if df_usuario_encoded.empty or df_usuario_encoded.sum().sum() == 0:
        return "Erro: Nenhuma característica de usuário corresponde ao modelo de dados.", []

    vetor_usuario = df_usuario_encoded.values

    # 2. Calcula a Similaridade do Cosseno
    # Compara o vetor do usuário com cada linha da matriz de features (cada destino)
    # O output é um array de similaridades, uma para cada destino.
    similaridades = cosine_similarity(vetor_usuario, matriz_features).flatten()

    # 3. Encontra os k destinos mais similares
    # Argumentos do array que dariam as maiores similaridades
    indices_similares = similaridades.argsort()[:-k-1:-1]

    # Recupera os nomes dos destinos e suas respectivas similaridades
    recomendacoes = []
    for i in indices_similares:
        recomendacoes.append({
            'Destino': destinos[i],
            'Similaridade': similaridades[i]
        })

    return recomendacoes

# --- CENÁRIO 1: Férias de Praia e Relaxamento no Verão (Curta Duração) ---
preferencias_praia = {
    'Tipo_Viagem': 'Praia',
    'Duracao': 'Curta',
    'Interesse': 'Relaxamento',
    'Estacao': 'Verao'
}

# --- CENÁRIO 2: Viagem Cultural e Histórica no Outono (Longa Duração) ---
preferencias_cultural = {
    'Tipo_Viagem': 'Cultural',
    'Duracao': 'Longa',
    'Interesse': 'Historia',
    'Estacao': 'Outono'
}

print("--- 🏖️ Recomendações: Praia, Relaxamento, Verão ---")
recs_praia = recomendar_destino(preferencias_praia, df_features, destinos, matriz_features, k=3)
for rec in recs_praia:
    print(f"Destino: {rec['Destino']} (Similaridade: {rec['Similaridade']:.4f})")

print("\n--- 🏛️ Recomendações: Cultural, Histórica, Outono ---")
recs_cultural = recomendar_destino(preferencias_cultural, df_features, destinos, matriz_features, k=3)
for rec in recs_cultural:
    print(f"Destino: {rec['Destino']} (Similaridade: {rec['Similaridade']:.4f})")